### ISSUE TITLE
1.15 Paper Startup Error

### ISSUE THREAD

**Issue by leasoncre** [Bssentials/Bssentials-2#29]
Startup error on game launch. plugin does not load :(
Java 8 x64, Paper Spigot 1.15.1

`[11:43:58] [Server thread/INFO]: [Essentials] Enabling Essentials v2.0.1-Bssentials*
[11:43:58] [Server thread/INFO]: [BssentialsEssentialsBridge]: Method not implemented: com.earth2me.essentials.I18n#onEnable
[11:43:58] [Server thread/INFO]: [BssentialsEssentialsBridge]: Method not implemented: com.earth2me.essentials.Console#setInstance
[11:43:58] [Server thread/ERROR]: Error occurred while enabling Essentials v2.0.1-Bssentials (Is it up to date?)
java.lang.NullPointerException: null
	at com.earth2me.essentials.Warps.<init>(Warps.java:20) ~[?:?]
	at com.earth2me.essentials.Essentials.onEnable(Essentials.java:192) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[11:43:58] [Server thread/INFO]: [Essentials] Disabling Essentials v2.0.1-Bssentials
[11:43:58] [Server thread/INFO]: [BssentialsEssentialsBridge]: Method not implemented: com.earth2me.essentials.I18n#onDisable`

**Comment by leasoncre** [comment]
Added EssentialsX and error no-longer happens. (EssX not officially supported 1.15 yet, but seems to be working)
Idk what EssentialsAPIBridge is supposed to do, because it conflicts with EssX..

Issue Closed
