### ISSUE TITLE
Bssentials fails to register commands

### ISSUE THREAD

**Issue by SSUPII** [Bssentials/Bssentials-2#31]
Running on Spigot 1.16.1.
There should have been something between "permission" and "is". There is in fact a double space (Doesn't look like it appears correctly on Github). What is it trying to define?
> [19:33:11] [Server thread/ERROR]: Error occurred while enabling Bssentials v3.0-b31 (Is it up to date?)
java.lang.IllegalArgumentException: The permission  is already defined!
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:699) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:691) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at bssentials.Bssentials.register(Bssentials.java:121) ~[?:?]
        at bssentials.Bssentials.onEnable(Bssentials.java:70) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:491) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:405) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.reload(CraftServer.java:873) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at org.bukkit.Bukkit.reload(Bukkit.java:642) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:755) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:740) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:386) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:355) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-ad703da-e2403a3]
        at java.lang.Thread.run(Thread.java:830) [?:?]

**Comment by iwillreku3206** [comment]
Also happens to me too! Bssentials is now useless for me since none of the commands work
