### ISSUE TITLE
Possible issues with 1.16.x?

### ISSUE THREAD

**Issue by Magicrafter13** [Bssentials/Bssentials-2#33]
Just added this to a fresh 1.16.1 spigot server (papermc), and it appears the plugin isn't ready for 1.16 yet, unless there's something odd with my setup.
```
[19:26:08 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[19:26:18 WARN]: Legacy plugin Bssentials v3.0-b31 does not specify an api-version.
(a little later)
[19:26:29 ERROR]: Error occurred while enabling Bssentials v3.0-b31 (Is it up to date?)
java.lang.IllegalArgumentException: The permission  is already defined!
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:724) ~[patched_1.16.1.jar:git-Paper-86]
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:716) ~[patched_1.16.1.jar:git-Paper-86]
        at bssentials.Bssentials.register(Bssentials.java:121) ~[?:?]
        at bssentials.Bssentials.onEnable(Bssentials.java:70) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-86]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-86]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-86]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-86]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-86]
        at java.lang.Thread.run(Thread.java:830) [?:?]
```

**Comment by pisaiah** [comment]
try build 32 from
https://ci.codemc.io/job/Fungus-Software/job/Bssentials/lastSuccessfulBuild/artifact/Bssentials/target/Bssentials3.jar

**Comment by Magicrafter13** [comment]
@IsaiahPatton no difference

**Comment by pisaiah** [comment]
what about build 33?
https://ci.codemc.io/job/Fungus-Software/job/Bssentials/lastBuild/artifact/Bssentials/target/Bssentials3.jar

**Comment by Magicrafter13** [comment]
```
[20:02:27 WARN]: Legacy plugin Bssentials v3.0-b33 does not specify an api-version.
[20:02:27 WARN]: Legacy plugin bPermissions v2.12.3 does not specify an api-version.
```
The warning still exists, but the error is gone now. Is build 33 the newest or are the newer versions? I download the plugin from https://dev.bukkit.org/projects/bssentials I'm not familiar with the site you've been linking to.

(Also should I close the issue now, since I assume the warning isn't that important?)

**Comment by Magicrafter13** [comment]
Wait, now I get an error every time a user joins! (Or at least every time I join...)
```
[20:09:12 ERROR]: Could not pass event PlayerJoinEvent to Bssentials v3.0-b33
java.lang.NullPointerException: null
        at bssentials.listeners.PlayerJoin.onPlayerJoin(PlayerJoin.java:31) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor7.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-86]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-86]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-86]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.PlayerConnection.tick(PlayerConnection.java:150) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.NetworkManager.a(NetworkManager.java:373) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:142) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1378) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-86]
        at java.lang.Thread.run(Thread.java:830) [?:?]
```
