### ISSUE TITLE
update to 1.20.6-1.21

### ISSUE THREAD

**Issue by Outfit8TSB** [Bssentials/Bssentials-2#45]
when update to 1.20.6 and 1.21
i want to use it as a library to run Netssentials, that uses 3 EssentialsX, Bssentials, Sunlight
to create an Portal site interface

**Comment by Outfit8TSB** [comment]
oh wait it works
```

D:\git\ign\SurvivalRad>java -jar radioactive-paperclip-1.20.6-R0.1-SNAPSHOT-reobf.jar
Starting org.bukkit.craftbukkit.Main
System Info: Java 21 (Java HotSpot(TM) 64-Bit Server VM 21.0.2+13-LTS-58) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
        RRRRRRRRR
        R       R ADIOACTIVE (TM)
        RRRRRRRR
        R       R
        R       R
                    ,,,         ,,,
          ;"   ^;     ;'   ",
          ;    s$$$$$$$s     ;
          ,  ss$$$$$$$$$$s  ,'
          ;s$$$$$$$$$$$$$$$
          $$$$$$$$$$$$$$$$$$
         $$$$P""Y$$$Y""W$$$$$
         $$$$  p"$$$"q  $$$$$
         $$$$  .$$$$$.  $$$$
          $$DcaU$$$$$$$$$$
by          "Y$$$"*"$$$Y"    aka
dcau            "$b.$$"     Panda

[07:21:45 ERROR]: **********************************************
[07:21:45 ERROR]: (!) #PlazmaXLeaves 및 #Radioactive의 모든 게이머와 지지자에게:
[07:21:45 ERROR]: 우리는 사랑하는 아기판다 푸바오에 대한 학대에 맞서고 있습니다. 푸바오는 열악한 환경에서 생활하고 있어 몸 전체에 상처가 있는 것으로 나타났습니다.
[07:21:45 ERROR]: 이것은 용납될 수 없습니다!
[07:21:45 ERROR]: 우리는 국제자연보전연맹(IUCN)에 이 사실을 고발하려는 청원에 동참하기로 결정을 내렸습니다. 우리는 워싱턴 조약(CITES)을 이 사태의 원인으로
[07:21:45 ERROR]: 지목하고 있습니다.
[07:21:45 ERROR]:
[07:21:45 ERROR]: 푸바오를 위하여 우리의 목소리를 울리게 만듭시다! 우리는 할 수 있습니다! #SupportFuBao #SaveFuBao #BringFuBaoBackToKorea #KoreaChinaFriendsForeverWithFuBao
[07:21:45 ERROR]: #supportfubao #savefubao #citessux #CITESSucks #bringfubaobacktokorea #koreachinafriendsforeverwithfubao  #PlazmaXLeaves #FuBao #푸바오 #福宝 #플라즈마X리브스 #푸바오와함께
[07:21:45 ERROR]: ENGLISH:
[07:21:45 ERROR]: (!) Attention all gamers and supporters of #PlazmaXLeaves and #Radioactive! We are taking a stand against the mistreatment of our beloved panda, Fu Bao. Recent reports have shown that Fu Bao is living in poor conditions, resulting in scars all
[07:21:45 ERROR]: over her body. This is unacceptable!
[07:21:45 ERROR]:
[07:21:45 ERROR]: We are joining the petition to report China's panda abuse to the International Union for Conservation of Nature (IUCN). We believe that the Convention on International Trade in Endangered Species (CITES) should be held accountable for allowing
[07:21:45 ERROR]: Fu Bao to live in such an environment.
[07:21:45 ERROR]:
[07:21:45 ERROR]: Join us in our protest for Fu Bao. Let's risk getting Radioactive into the list of shame to make our voices heard. Together, we can make a difference. #SupportFuBao #SaveFuBao #BringFuBaoBackToKorea #KoreaChinaFriendsForeverWithFuBao
[07:21:45 ERROR]: #supportfubao #savefubao #citessux #CITESSucks #bringfubaobacktokorea #koreachinafriendsforeverwithfubao  #PlazmaXLeaves #FuBao #푸바오 #福宝 #플라즈마X리브스 #푸바오와함께
[07:21:45 ERROR]:
[07:21:45 ERROR]: *******************************************************
[07:21:45 WARN]: Warning! RadioActive may cause unexpected problems, so be sure to test it thoroughly before using it on a public server.
[07:21:45 ERROR]: *********************** CAUTION ***********************
[07:21:45 ERROR]: This version is a development version of RadioActive.
[07:21:45 ERROR]: Nobody knows what kind of problem you're going to have, and there's always the possibility of unexpected problems.
[07:21:45 ERROR]: Never use this version on a public server, and after you've tested it enough before using it!
[07:21:45 ERROR]: *******************************************************
[07:21:47 WARN]: [PlazmaConfigurations] Default configuration optimization is enabled. It may have some impact on gameplay.
[07:21:47 WARN]: [PlazmaConfigurations] To disable default configuration optimization, type "-DPlazma.disableConfigOptimization" before the -jar in the server startup command.
[07:21:55 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[07:21:56 INFO]: Loaded 1175 recipes
[07:21:56 INFO]: Loaded 1276 advancements
[07:22:00 INFO]: Starting minecraft server version 1.20.6
[07:22:00 INFO]: Loading properties
[07:22:00 INFO]: This server is running RadioActive version 1.20.6-DEV-feat/citessucks@d20006b (2024-07-29T13:45:17Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
[07:22:01 INFO]: Server Ping Player Sample Count: 12
[07:22:01 INFO]: Using 4 threads for Netty based IO
[07:22:01 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[07:22:01 INFO]: [HalloweenManager] Updating Spooky Season and Halloween epoch...
[07:22:01 INFO]: [HalloweenManager] Successfully updated Spooky Season and Halloween epoch
[07:22:01 WARN]: [Pufferfish] SIMD operations are available for your server, but are not configured!
[07:22:01 WARN]: [Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[07:22:01 WARN]: [Pufferfish] If you have already added this flag, then SIMD operations are not supported on your JVM or CPU.
[07:22:01 WARN]: [Pufferfish] Debug: Java: 21.0.2, test run: true
[07:22:01 INFO]: Default game type: SURVIVAL
[07:22:01 INFO]: Generating keypair
[07:22:01 INFO]: Starting Minecraft server on *:25562
[07:22:01 INFO]: Using default channel type
[07:22:01 INFO]: Paper: Using Java compression from Velocity.
[07:22:01 INFO]: Paper: Using Java cipher from Velocity.
[07:22:01 ERROR]: [ModernPluginLoadingStrategy] Ambiguous plugin name 'Bssentials' for files 'plugins\Bssentials3.jar' and 'plugins\Bssentials-Bukkit.jar' in 'plugins'
[07:22:02 WARN]: [org.bukkit.craftbukkit.v1_20_R4.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[07:22:09 WARN]: Legacy plugin LunaChat v3.0.16 does not specify an api-version.
[07:22:09 WARN]: Legacy plugin Bssentials v3.0-b35 does not specify an api-version.
[07:22:09 INFO]: [ViaVersion] Loading server plugin ViaVersion v5.0.0
[07:22:09 INFO]: [ViaVersion] ViaVersion 5.0.0 is now loaded. Registering protocol transformers and injecting...
[07:22:10 INFO]: [ViaVersion] Loading block connection mappings ...
[07:22:10 INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[07:22:10 INFO]: [ViaBackwards] Loading translations...
[07:22:10 INFO]: [ViaBackwards] Registering protocols...
[07:22:11 INFO]: [ViaRewind] Registering protocols...
[07:22:11 INFO]: [WorldEdit] Loading server plugin WorldEdit v7.3.3+6788-6359df8
[07:22:12 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@137a035b]
[07:22:12 INFO]: [ViaBackwards] Loading server plugin ViaBackwards v5.0.0
[07:22:12 INFO]: [Slimefun] Loading server plugin Slimefun vDev - 1148
[07:22:12 INFO]: [floodgate] Loading server plugin floodgate v2.2.3-SNAPSHOT (b109-49bd564)
[07:22:13 INFO]: [floodgate] Floodgate를 부팅하는 데 877밀리초가 걸렸습니다
[07:22:13 INFO]: [CustomJoinAndQuitMessages] Loading server plugin CustomJoinAndQuitMessages v1.8.0-b0
[07:22:13 INFO]: [spark] Loading server plugin spark v1.10.92
[07:22:13 INFO]: [VoxelSniper] Loading server plugin VoxelSniper v6.1.2
[07:22:13 INFO]: [ViaRewind] Loading server plugin ViaRewind v4.0.0
[07:22:13 INFO]: [SlimefunNukes] Loading server plugin SlimefunNukes v3.2.5
[07:22:13 INFO]: [MiniMOTD] Loading server plugin MiniMOTD v2.1.1
[07:22:13 INFO]: [LunaChat] Loading server plugin LunaChat v3.0.16
[07:22:13 INFO]: [Geyser-Spigot] Loading server plugin Geyser-Spigot v2.4.0-SNAPSHOT
[07:22:14 INFO]: [Geyser-Spigot] 확장을 불러오는 중...
[07:22:14 INFO]: [Geyser-Spigot] 확장 0개를 불러옴
[07:22:14 INFO]: [Essentials] Loading server plugin Essentials v2.21.0-dev+93-3a6fdd9
[07:22:14 INFO]: [Bssentials] Loading server plugin Bssentials v3.0-b35
[07:22:14 INFO]: Server permissions file permissions.yml is empty, ignoring it
[07:22:14 INFO]: [WorldEdit] Enabling WorldEdit v7.3.3+6788-6359df8
[07:22:14 INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[07:22:14 INFO]: WEPIF: Using the Bukkit Permissions API.
[07:22:14 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R4.PaperweightAdapter as the Bukkit adapter
[07:22:15 INFO]: [ViaRewind] Enabling ViaRewind v4.0.0
[07:22:15 INFO]: Preparing level "world"
[07:22:15 INFO]: Preparing start region for dimension minecraft:overworld
[07:22:16 INFO]: Time elapsed: 877 ms
[07:22:16 INFO]: Preparing start region for dimension minecraft:the_nether
[07:22:16 INFO]: Time elapsed: 116 ms
[07:22:16 INFO]: Preparing start region for dimension minecraft:the_end
[07:22:17 INFO]: Time elapsed: 110 ms
[07:22:17 INFO]: [ViaVersion] Enabling ViaVersion v5.0.0
[07:22:17 INFO]: [ViaVersion] ViaVersion detected server version: 1.20.5-1.20.6 (766)
[07:22:17 INFO]: [ViaBackwards] Enabling ViaBackwards v5.0.0
[07:22:17 INFO]: [Slimefun] Enabling Slimefun vDev - 1148
[07:22:17 INFO]: [Slimefun] Paper was detected! Performance optimizations have been applied.
[07:22:17 INFO]: [Slimefun] Creating directories...
[07:22:17 INFO]: [Slimefun] Loading language files...
[07:22:17 ERROR]: [dough: skins] Failed to detect skull nbt methods
java.lang.NoSuchMethodException: net.minecraft.world.level.block.entity.TileEntitySkull.a(com.mojang.authlib.GameProfile)
        at java.base/java.lang.Class.getMethod(Class.java:2395) ~[?:?]
        at Slimefun4-Dev (1).jar/io.github.thebusybiscuit.slimefun4.libraries.dough.skins.nms.PlayerHeadAdapter18.<init>(PlayerHeadAdapter18.java:23) ~[Slimefun4-Dev (1).jar:?]
        at Slimefun4-Dev (1).jar/io.github.thebusybiscuit.slimefun4.libraries.dough.skins.nms.PlayerHeadAdapter.get(PlayerHeadAdapter.java:31) ~[Slimefun4-Dev (1).jar:?]
        at Slimefun4-Dev (1).jar/io.github.thebusybiscuit.slimefun4.libraries.dough.skins.PlayerHead.<clinit>(PlayerHead.java:23) ~[Slimefun4-Dev (1).jar:?]
        at Slimefun4-Dev (1).jar/io.github.thebusybiscuit.slimefun4.utils.SlimefunUtils.getCustomHead(SlimefunUtils.java:246) ~[Slimefun4-Dev (1).jar:?]
        at Slimefun4-Dev (1).jar/io.github.thebusybiscuit.slimefun4.core.services.localization.Language.<init>(Language.java:52) ~[Slimefun4-Dev (1).jar:?]
        at Slimefun4-Dev (1).jar/io.github.thebusybiscuit.slimefun4.core.services.LocalizationService.<init>(LocalizationService.java:67) ~[Slimefun4-Dev (1).jar:?]
        at Slimefun4-Dev (1).jar/io.github.thebusybiscuit.slimefun4.implementation.Slimefun.onPluginStart(Slimefun.java:300) ~[Slimefun4-Dev (1).jar:?]
        at Slimefun4-Dev (1).jar/io.github.thebusybiscuit.slimefun4.implementation.Slimefun.onEnable(Slimefun.java:241) ~[Slimefun4-Dev (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[radioactive-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[radioactive-1.20.6.jar:1.20.6-DEV-d20006b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[radioactive-1.20.6.jar:1.20.6-DEV-d20006b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[radioactive-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:630) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:579) ~[?:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:685) ~[radioactive-1.20.6.jar:1.20.6-DEV-d20006b]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:447) ~[radioactive-1.20.6.jar:1.20.6-DEV-d20006b]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[radioactive-1.20.6.jar:1.20.6-DEV-d20006b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1158) ~[radioactive-1.20.6.jar:1.20.6-DEV-d20006b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[radioactive-1.20.6.jar:1.20.6-DEV-d20006b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[07:22:17 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[07:22:17 INFO]: [Slimefun] Loaded language "en"
[07:22:17 INFO]: [Slimefun] Available languages: en, de, fr, it, es, ru, pl, uk, sv, nl, da, cs, ro, bg, pt, pt-BR, hu, lv, sk, vi, id, zh-CN, zh-TW, ja, ko, he, ar, tr, fa, th, tl
[07:22:17 INFO]: [Slimefun] Using legacy storage for player data
[07:22:17 INFO]: [Slimefun] Enabled Analytics Service
[07:22:17 INFO]: [Slimefun] MetricsModule does not exist, downloading...
[07:22:17 INFO]: [Slimefun] Starting Auto-Updater...
[07:22:17 INFO]: [Slimefun] Loading GEO-Resources...
[07:22:17 INFO]: [Slimefun] Loading Tags...
[07:22:17 INFO]: [Slimefun] Loading items...
[07:22:17 INFO]: [Slimefun] # Starting download of MetricsModule build: #29
[07:22:18 INFO]: [Slimefun] Loading researches...
[07:22:18 WARN]: [Slimefun] Failed to start metrics as the file could not be downloaded.
[07:22:18 INFO]: [Slimefun] Loading Wiki pages...
[07:22:18 INFO]: [Slimefun] Registering listeners...
[07:22:18 INFO]: [Slimefun] Loading Third-Party plugin integrations...
[07:22:18 INFO]: [Slimefun] Hooked into Plugin: WorldEdit v7.3.3+6788-6359df8
[07:22:18 INFO]: [Slimefun] Slimefun has finished loading in 1.25s
[07:22:18 INFO]: [floodgate] Enabling floodgate v2.2.3-SNAPSHOT (b109-49bd564)
[07:22:18 INFO]: [CustomJoinAndQuitMessages] Enabling CustomJoinAndQuitMessages v1.8.0-b0
[07:22:19 INFO]: [spark] Enabling spark v1.10.92
[07:22:19 INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[07:22:19 INFO]: [spark] Starting background profiler...
[07:22:19 INFO]: [spark] The async-profiler engine is not supported for your os/arch (windows10/amd64), so the built-in Java engine will be used instead.
[07:22:19 INFO]: [VoxelSniper] Enabling VoxelSniper v6.1.2
[07:22:19 INFO]: [VoxelSniper] Registered 69 Sniper Brushes with 137 handles.
[07:22:19 INFO]: [VoxelSniper] Registered Sniper Listener.
[07:22:19 INFO]: [SlimefunNukes] Enabling SlimefunNukes v3.2.5
[07:22:19 INFO]: [MiniMOTD] Enabling MiniMOTD v2.1.1
[07:22:20 INFO]: [LunaChat] Enabling LunaChat v3.0.16*
[07:22:20 INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.4.0-SNAPSHOT
[07:22:20 INFO]: [Essentials] Enabling Essentials v2.21.0-dev+93-3a6fdd9
[07:22:20 INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[07:22:20 INFO]: [Essentials] No kits found to migrate.
[07:22:21 INFO]: [Essentials] Loaded 39121 items from items.json.
[07:22:21 INFO]: [Essentials] Using locale ko_KR
[07:22:21 INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[07:22:21 INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[07:22:21 INFO]: [Essentials] Using superperms-based permissions.
[07:22:21 INFO]: [Bssentials] Enabling Bssentials v3.0-b35*
[07:22:21 INFO]: [Bssentials] ===========================
[07:22:21 INFO]: [Bssentials] EssentialsX warps found!
[07:22:21 INFO]: [Bssentials] To use your old warps move them from the /Essentials/warps/ folder into /Bssentials/warps/
[07:22:21 INFO]: [Bssentials] ===========================
[07:22:21 WARN]: [Bssentials] Could not save config.yml to plugins\Bssentials\config.yml because config.yml already exists.
[07:22:21 WARN]: [Bssentials] Could not save info.txt to plugins\Bssentials\info.txt because info.txt already exists.
[07:22:21 WARN]: [Bssentials] Could not save motd.txt to plugins\Bssentials\motd.txt because motd.txt already exists.
[07:22:21 WARN]: [Bssentials] Could not save rules.txt to plugins\Bssentials\rules.txt because rules.txt already exists.
[07:22:21 INFO]: [Bssentials] Loading configuration...
[07:22:21 INFO]: [Bssentials] Registering commands...
[07:22:21 INFO]: [Bssentials] Registered 8 commands
[07:22:21 INFO]: [Geyser-Spigot] ******************************************
[07:22:21 INFO]: [Geyser-Spigot]
[07:22:21 INFO]: [Geyser-Spigot] Geyser 버전 2.4.0-b621 (git-master-a85b312)(을)를 불러오는 중...
[07:22:21 INFO]: [Geyser-Spigot]
[07:22:21 INFO]: [Geyser-Spigot] ******************************************
[07:22:26 INFO]: [Geyser-Spigot] Geyser를 0.0.0.0:19133에서 시작합니다
[07:22:26 INFO]: [Geyser-Spigot] 완료! (4.693초) /geyser help로 도움말을 참조하세요.
[07:22:26 INFO]: Running delayed init tasks
[07:22:26 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[07:22:26 INFO]: [Slimefun] Collecting Snapshots of all Recipes...
[07:22:26 INFO]: [Slimefun] Found 1,175 Recipes!
[07:22:26 INFO]: [Essentials] 버전 정보를 가져오는중...
[07:22:26 INFO]:
[07:22:26 INFO]: ######################### - Slimefun vDev - 1148 - #########################
[07:22:26 INFO]:
[07:22:26 INFO]: Successfully loaded 557 Items and 259 Researches
[07:22:26 INFO]: ( 555 Items from Slimefun, 2 Items from 1 Addons )
[07:22:26 INFO]:
[07:22:26 INFO]: Slimefun is an Open-Source project that is kept alive by a large community.
[07:22:26 INFO]: Consider helping us maintain this project by contributing on GitHub!
[07:22:26 INFO]:
[07:22:26 INFO]:  - Source Code:  https://github.com/Slimefun/Slimefun4
[07:22:26 INFO]:  - Wiki:         https://github.com/Slimefun/Slimefun4/wiki
[07:22:26 INFO]:  - Addons:       https://github.com/Slimefun/Slimefun4/wiki/Addons
[07:22:26 INFO]:  - Bug Reports:  https://github.com/Slimefun/Slimefun4/issues
[07:22:26 INFO]:  - Discord:      https://discord.gg/slimefun
[07:22:26 INFO]:
[07:22:26 INFO]: [Slimefun] Loading Blocks for World "world"
[07:22:26 INFO]: [Slimefun] This may take a long time...
[07:22:26 INFO]: [Slimefun] Loading Blocks... 100% (FINISHED - 0ms)
[07:22:26 INFO]: [Slimefun] Loaded a total of 0 Blocks for World "world"
[07:22:26 INFO]: [Slimefun] Loading Blocks for World "world_nether"
[07:22:26 INFO]: [Slimefun] This may take a long time...
[07:22:26 INFO]: [Slimefun] Loading Blocks... 100% (FINISHED - 0ms)
[07:22:26 INFO]: [Slimefun] Loaded a total of 0 Blocks for World "world_nether"
[07:22:26 INFO]: [Slimefun] Loading Blocks for World "world_the_end"
[07:22:26 INFO]: [Slimefun] This may take a long time...
[07:22:26 INFO]: [Slimefun] Loading Blocks... 100% (FINISHED - 0ms)
[07:22:26 INFO]: [Slimefun] Loaded a total of 0 Blocks for World "world_the_end"
[07:22:26 INFO]: [dough: protection] Loading Protection Modules...
[07:22:26 INFO]: [dough: protection] This may happen more than once.
[07:22:26 INFO]: [Bssentials] Bssentials Version 3.0-b35
[07:22:26 INFO]: Done (26.470s)! For help, type "help"
[07:22:26 INFO]: Join https://m.cafe.naver.com/ca-fe/fubaofromkorea Now! #SaveFubao #CITESSucks.
[07:22:26 INFO]: #SaveFubao #CITESSucks Sign The Petition Below:
[07:22:26 INFO]: https://docs.google.com/forms/d/1T0DPCowYoSYaPk5hPvpcElN4bQx0KYYxB_7vqdiQMlc/viewform?edit_requested=tr
[07:22:26 INFO]: https://form.naver.com/response/Y2Ew5v7oU_6I3ME2PuZRxg
[07:22:26 WARN]: [ViaVersion] There is a newer plugin version available: 5.0.2, you're on: 5.0.0
[07:22:26 INFO]: [MiniMOTD] There is an update available for MiniMOTD!
[07:22:26 INFO]: [MiniMOTD] This server is running version v2.1.1, which is 1 versions outdated.
[07:22:26 INFO]: [MiniMOTD] Download the latest version, v2.1.2 from GitHub at the link below:
[07:22:26 INFO]: [MiniMOTD] https://github.com/jpenilla/MiniMOTD/releases/tag/v2.1.2
[07:22:26 WARN]: [Essentials] 구버전의 13 EssentialsX 개발 빌드를 사용하고 있습니다!
[07:22:26 WARN]: [Essentials] 여기서 다운로드: https://essentialsx.net/downloads.html
[07:22:27 INFO]: [Slimefun] Slimefun is already up to date!
```
